### ISSUE TITLE
Call for Speakers

### ISSUE THREAD

**Issue by joshuamabina** [forlooptanzania/forlooptanzania.github.io#1]
We're looking for speakers for our next meetup.

- Theme: **The Next Billion: Harder, Better, Faster, Stronger.**
- When: **Wednesday, October, 17th at 5pm**
- Where: **[Seedspace, 7th Floor, Tanzaniate Park 38, New Bagamoyo Road][1]**

[1]: https://goo.gl/maps/eEcfXyFBac52

**How do I submit a talk?**

1. Comment on this current issue.
2. Promote your talk on twitter. Include link to your comment.
3. Use hashtags: `#forloop`, `#forlooptanzania`, `#tanzania`, `#speaking`.
4. Remember to tag: `@forLoopAfrica` `@forLoopTanzania`

**How long should my talk be?**

Ten minutes. There won't be any formal Q&A; we encourage attendees to ask
questions in person later. We also try to introduce you well enough so you can
speed through any self-bio slides.

**What should be in my talk submission?**

Just a few sentences describing what you want to talk about would be great.

**What happens after I submit my talk?**

We will follow up with you via email! It may take a few days.

**What's the A/V situation?**

We'll have HDMI to plug into (for video and audio) and a mic for you to use.
Let us know if you need any fancy adapters (we'll have some Apple ones).

**Do I need to submit my slides beforehand?**

Nope, but please show up at least 1 hour before your talk.

**Comment by OlivierJM** [comment]
I would love to speak at this one 

Title: State of State Management in modern application

**Comment by kenessajr** [comment]
Count me as a speaker. 

```Title: undefined yet. ```

**Comment by brucealgorithm** [comment]
Preacher here !!!!

Title: Building the A-Team

Spit fire on 21st century tools for agile development processes and best-practise to maximise productivity in an Agile Team (The A-Team).
Get ready, i'll be making it a little bit practical so we can actually collaborate with agile team in Tanzania from Nigeria and see Africa take over the world!!!!!!!.

See you there... Pastor Bruce Lucas - @brucealgorithm

**Comment by jestrux** [comment]
Title: React from a non-Beleiver's perspective.

**Comment by jestrux** [comment]
The progressive in Progressive Web Apps(PWAs)

Important discussion into the way PWAs should be built which is by progressively enhancing your app experience by iteratively fixing the most crucial problems or hindrances based on your app's context.

**Comment by issyzac** [comment]
Title: Untitled Management Talk

Body: Developers are like Kids: Managing the Sugar Jar

**Comment by droidada** [comment]
Hey everyone, I'd love to speak at this event. 
Here are a couple of ideas for talks I have in mind

One is a technical topic
**Title**: Web Components, the future of single responsibility principle
**Description**: the presentation will be an introduction to the world of web components. participants will learn what they are, the basics of how to create them and their usefulness in the future of web.

Another is a social topic
**Title**: Charting a career in software development
**Description**: in this presentation I will talk about my experience charting a career in software development. The dos, don'ts and lessons learnt.

**Comment by abesamma** [comment]
I'd like to give a talk!

Title: Javascript Bricolage: a story of user empowerment feat. TiddlyWiki
