### ISSUE TITLE
Join our awesome WhatsApp group

### ISSUE THREAD

**Issue by issyzac** [forlooptanzania/forlooptanzania.github.io#3]
Follow this link to join the workshop's WhatsApp group: https://chat.whatsapp.com/GlvKRg6a9q27G70sQFBjSm

**Comment by veemish** [comment]
looks like the link was revoked have been trying to join the watsapp group,

**Comment by kaiaseamus** [comment]
Cool WhatsApp statuses are one of the effective ways to build an attractive image. Moreover, it helps to share your ideas, thoughts, etc through an outstanding technique
https://bit.ly/2DMHEx6

**Comment by joshuamabina** [comment]
> looks like the link was revoked have been trying to join the watsapp group,

Thank you for this. We will update.
